# Generated by Django 4.2.16 on 2026-06-25 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyCertificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipient_name', models.CharField(max_length=255, verbose_name='Recipient Name')),
                ('certificate_name', models.CharField(default='Certificate of Achievement', max_length=255, verbose_name='Certificate Title')),
                ('certificate_number', models.CharField(max_length=100, unique=True, verbose_name='Certificate Number')),
                ('issue_date', models.DateField(verbose_name='Issue Date')),
                ('expiry_date', models.DateField(blank=True, null=True, verbose_name='Expiry Date')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Company Certificate',
                'verbose_name_plural': 'Company Certificates',
                'ordering': ['-issue_date'],
            },
        ),
    ]
