# Generated by Django 4.2.16 on 2026-06-25 17:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_companycertificate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='companycertificate',
            name='expiry_date',
        ),
    ]
