# Generated by Django 4.2.16 on 2026-06-26 06:22

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_companycertificate_expiry_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now, verbose_name='Report Date')),
                ('location', models.CharField(choices=[('SHERGHATI', 'Sherghati'), ('TEKARI', 'Tekari'), ('AURANGABAD', 'Aurangabad'), ('JAHANABAD', 'Jahanabad'), ('NAWADA', 'Nawada')], max_length=50, verbose_name='Location')),
                ('name', models.CharField(max_length=255, verbose_name='Employee Name')),
                ('year', models.CharField(max_length=4, verbose_name='Year')),
                ('volume_num', models.CharField(max_length=100, verbose_name='Volume Number')),
                ('num_of_deed', models.IntegerField(verbose_name='Number of Deeds')),
                ('num_of_page', models.IntegerField(verbose_name='Number of Pages')),
                ('pdf_deed', models.BooleanField(default=False, verbose_name='PDF (Deed)')),
                ('indexing', models.BooleanField(default=False, verbose_name='Indexing')),
                ('uploading', models.BooleanField(default=False, verbose_name='Uploading')),
                ('metadata', models.BooleanField(default=False, verbose_name='Meta Data')),
            ],
            options={
                'verbose_name': 'Daily Report',
                'verbose_name_plural': 'Daily Reports',
                'ordering': ['-date', 'location'],
            },
        ),
    ]
