# Generated by Django 4.2.16 on 2026-06-26 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_dailyreport'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailyreport',
            name='year',
            field=models.CharField(max_length=9, verbose_name='Year'),
        ),
    ]
