# Generated by Django 4.2.16 on 2026-06-26 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_dailyreport_year'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='dailyreport',
            constraint=models.UniqueConstraint(fields=('year', 'volume_num', 'location'), name='unique_year_volume_location'),
        ),
    ]
