# Generated by Django 4.2.16 on 2026-06-26 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_dailyreport_unique_year_volume_location'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='dailyreport',
            name='unique_year_volume_location',
        ),
        migrations.AlterField(
            model_name='dailyreport',
            name='location',
            field=models.CharField(choices=[('SHERGHATI', 'Sherghati'), ('TEKARI', 'Tekari'), ('AURANGABAD', 'Aurangabad'), ('JAHANABAD', 'Jahanabad'), ('NAWADA', 'Nawada'), ('NALANDA', 'Nalanda'), ('HILSA', 'Hilsa')], max_length=50, verbose_name='Location'),
        ),
    ]
