# Generated by Django 4.2.16 on 2026-06-27 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_remove_dailyreport_unique_year_volume_location_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailyreport',
            name='QC',
            field=models.BooleanField(default=False, verbose_name='QC'),
        ),
    ]
