# Generated by Django 4.2.16 on 2026-06-29 09:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_dailyreport_qc'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailyreport',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2026, 6, 28, 9, 31, 21, 203889, tzinfo=datetime.timezone.utc), verbose_name='Created At'),
            preserve_default=False,
        ),
    ]
