# Generated by Django 4.2.16 on 2026-06-29 09:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_dailyreport_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dailyreport',
            name='created_at',
        ),
    ]
