# Generated by Django 4.2.16 on 2026-06-29 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_dailyreport_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailyreport',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Created At'),
        ),
    ]
