# Generated by Django 4.2.16 on 2026-07-01 11:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0012_alter_dailyreport_created_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='UploadingRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Employee Name')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Uploaded At')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Uploaded By')),
                ('daily_report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uploading_records', to='core.dailyreport', verbose_name='Daily Report')),
            ],
            options={
                'verbose_name': 'Uploading Record',
                'verbose_name_plural': 'Uploading Records',
            },
        ),
        migrations.CreateModel(
            name='QCRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Employee Name')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='QC Verified At')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='QC Verified By')),
                ('daily_report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='qc_records', to='core.dailyreport', verbose_name='Daily Report')),
            ],
            options={
                'verbose_name': 'QC Record',
                'verbose_name_plural': 'QC Records',
            },
        ),
        migrations.CreateModel(
            name='PDFRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Employee Name')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Created At')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('daily_report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pdf_records', to='core.dailyreport', verbose_name='Daily Report')),
            ],
            options={
                'verbose_name': 'PDF Record',
                'verbose_name_plural': 'PDF Records',
            },
        ),
        migrations.CreateModel(
            name='MetadataRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Employee Name')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Metadata Entered At')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Metadata Entered By')),
                ('daily_report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='metadata_records', to='core.dailyreport', verbose_name='Daily Report')),
            ],
            options={
                'verbose_name': 'Metadata Record',
                'verbose_name_plural': 'Metadata Records',
            },
        ),
        migrations.CreateModel(
            name='IndexingRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Employee Name')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Indexed At')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Indexed By')),
                ('daily_report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='indexing_records', to='core.dailyreport', verbose_name='Daily Report')),
            ],
            options={
                'verbose_name': 'Indexing Record',
                'verbose_name_plural': 'Indexing Records',
            },
        ),
    ]
