# Generated by Django 4.2.16 on 2026-07-01 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_uploadingrecord_qcrecord_pdfrecord_metadatarecord_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailyreport',
            name='num_of_deed',
            field=models.IntegerField(blank=True, null=True, verbose_name='Number of Deeds'),
        ),
    ]
