# Generated by Django 4.2.16 on 2026-07-08 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_alter_dailyreport_num_of_deed'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailyreport',
            name='scanning',
            field=models.BooleanField(default=True, verbose_name='Scanning'),
        ),
        migrations.AlterField(
            model_name='dailyreport',
            name='location',
            field=models.CharField(choices=[('SHERGHATI', 'Sherghati'), ('TEKARI', 'Tekari'), ('AURANGABAD', 'Aurangabad'), ('JAHANABAD', 'Jahanabad'), ('NAWADA', 'Nawada'), ('NALANDA', 'Nalanda'), ('HILSA', 'Hilsa'), ('ROSARA', 'Rosara'), ('KISHANPUR', 'Kishanpur'), ('DARBHANGA', 'Darbhanga'), ('BAHERA', 'Bahera'), ('DALSINGHSARAI', 'Dalsinghsarai'), ('BENIPATTI', 'Benipatti'), ('PHULPARAS', 'Phulparas'), ('JHANJHARPUR', 'Jhanjharpur'), ('JAINAGAR', 'Jainagar'), ('SAMASTIPUR', 'Samastipur'), ('KARAMGANJ', 'Karamganj'), ('KHAJAULI', 'Khajauli')], max_length=50, verbose_name='Location'),
        ),
    ]
