# Generated by Django 4.2.16 on 2026-07-08 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_dailyreport_scanning_alter_dailyreport_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailyreport',
            name='location',
            field=models.CharField(choices=[('SHERGHATI', 'Sherghati'), ('TEKARI', 'Tekari'), ('AURANGABAD', 'Aurangabad'), ('JAHANABAD', 'Jahanabad'), ('NAWADA', 'Nawada'), ('NALANDA', 'Nalanda'), ('HILSA', 'Hilsa'), ('ROSARA', 'Rosara'), ('KISHANPUR', 'Kishanpur'), ('DARBHANGA', 'Darbhanga'), ('BAHERA', 'Bahera'), ('DALSINGHSARAI', 'Dalsinghsarai'), ('BENIPATTI', 'Benipatti'), ('PHULPARAS', 'Phulparas'), ('JHANJHARPUR', 'Jhanjharpur'), ('JAINAGAR', 'Jainagar'), ('SAMASTIPUR', 'Samastipur'), ('KAMTAUL', 'Kamtaul'), ('KHAJAULI', 'Khajauli')], max_length=50, verbose_name='Location'),
        ),
    ]
