# Generated by Django 4.2.16 on 2026-07-24 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_alter_dailyreport_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailyreport',
            name='district',
            field=models.CharField(blank=True, choices=[('GAYA', 'Gaya'), ('NALANDA', 'Nalanda'), ('DARBHANGA', 'Darbhanga')], max_length=20, verbose_name='District'),
        ),
    ]
